### PR TITLE
Added semi-automatic car model recognition + fixed update frequency.

### PR DESCRIPTION
**Pull request by fetzu**
I took a shot at implementing some sort of semi-automatic car model recognition to lower the difficulty of entry.  

Unfortunately, this has **some caveats** (for now):
1. It does not work with Model Y (as I do not have output for reference, if someone can provide me some I'll gladly add this).
2. It does not work with exotic trims and configs. 

Setting it manually according to the list will always yield the best results.

**EDIT**: This also now includes some updates to the build pipelines (to allow for building on both amd64 and arm) and an alignment of the update frequencies according to Iternio's/ABRP's recommended values.

### CODE REVIEW

**Comment by fetzu** [comment]
**NOTE**: Added a "fix" to align update frequency to the recommended values today.

**Comment by jheredianet** [comment]
> **NOTE**: Added a "fix" to align update frequency to the recommended values today.

I'm just curious. If the car is parked (not driving or charing), why to send data to ABRP every 30s? Before it was every 10 mins. Is there any special reason?

**Comment by fetzu** [comment]
> I'm just curious. If the car is parked (not driving or charing), why to send data to ABRP every 30s? Before it was every 10 mins. Is there any special reason?

Hey Juan, the change in frequency came after a user opened [an issue on my fork of the repo](https://github.com/fetzu/teslamate-abrp/issues/3) when he noticed that his car was shown as "offline" in ABRP after a while.

I dug a little and found that Iternio actually recommends against updating less than once every 30 seconds in their [API doc](https://documenter.getpostman.com/view/7396339/SWTK5a8w). I agree with you that it seems a little excessive, but anything less and the car would potentially be considered "offline" by ABRP.

If you worry that it is too much, feel free to revert the changes by editing the values in the loop at line 260 (see https://github.com/letienne/teslamate-abrp/pull/5/commits/ac49644d73f60fed56c1699a08e206d84763e788).

Hope this answers your question !

**Comment by fetzu** [comment]
NOTE: This PR has transformed into a huge mess. I am separating the two features and creating new "clean" PRs for dedicated branches.

**Pull request closed without merging**
